### ISSUE TITLE
Unable to get property 'toString' of undefined or null reference

### ISSUE THREAD

**Issue by skyfox2k** [julianshapiro/velocity#530] opened 2015-05-29 04:53 UTC
Issue in IE10 and lower (have not tried 11). The code "var n=r.toString().match(/blur\(([0-9]+[A-z]+)\)/i)" is highlighted with the error in the console. This seems to be related with the fact I use blur in my site.

Any ideas on how to fix?

The site is www.skyfoxdesign.com/wp

**Comment by ydaniv** [comment] 2015-05-30 21:07
Sorry, but you'll have to reproduce this issue in a jsFiddle with a non-minified version.

**Comment by Rycochet** [comment] 2016-05-06 08:32
Closing as no fiddle, and due to IE10 being dropped by Microsoft it's not a priority - please re-open if it occurs in Edge and you can supply a fiddle.

**Closed by Rycochet** 2016-05-06 08:32 UTC
