### ISSUE TITLE
Feature request: Option Functions

### ISSUE THREAD

**Issue by Wouter125** [julianshapiro/velocity#850] opened 2018-02-26 11:20 UTC
Hiya! I know you are currently migrating everything to v2.0 but I would like to request a feature. We already have value functions, but now that I have certain separate elements in one Velocity function that I would like to delay step by step I would love to write a small little return function for it. Instead I need to include Velocity UI (not anymore in near feature), register a custom effect (Not sure how to do this in 2.0), and then assign that effect with stagger.

I would prefer to do it more like this;

    Velocity(overlays, { 
        transform: ['translateY(0%)', 'translateY(-100%)']
    }, {
        duration: 400,
        delay: function(i, total, elements) {
            return (i * 20)
        },
        complete: function(elements, activeCall) {
            removeContainer();
        }
    })

Not even sure if this is possible. Thanks for all your hard work and efforts so far.

**Comment by Rycochet** [comment] 2018-02-26 11:43
Duplicate of #789 
It'll get in there relatively soon - various options are valid on different things (global, animation, and element) - so it needs a combination of documentation and double-checking what's going to be allowed :-)

**Closed by Rycochet** 2018-02-26 11:43 UTC
