### ISSUE TITLE
Velocity V2 Stable

### ISSUE THREAD

**Issue by riiccardo** [julianshapiro/velocity#840] opened 2018-02-12 07:17 UTC
Hey   thanks for great animation plugin i love this plugin more than other animation framework ^-^:+1:

 ### When the new version becomes ( stable ) ? And when will be released? :thinking: 

 cuz some of the animation in newer version dosent work.
for example animation onClick just add velocity-animate class and then nothing happen just addClass and dont run the animation...  

TnQ :heart: 

===============================================

I found my problem that was my bad 🙃   visibility and display

 work on fewer version like V1.5.0 but dose'nt work on V2  👇 

`$element.velocity({ opacity: 0 }, { duration: 300, visibility: "hidden" })`

**i must use visibility in property like this** 👇 

`$element.velocity({ opacity: 0, visibility: "hidden" }, { duration: 300 })`

my fault is using visibility and display in options 

in V2 display and visibility becomes a property 

and These changes have not yet been applied to the site http://velocityjs.org/#displayAndVisibility

for more information about V2 check this link 

https://github.com/julianshapiro/velocity/blob/master/V2_CHANGES.md

# one of the changes i dont understand it yet 🤔 💭 
Transforms - Use these directly within CSS, don't try the old shortcuts as they don't exist.
Can you explain to us in this case?

=================================

understood transform too 😆 

in fewer version V1.5.0 transform must be like this
`$element.velocity({ translateX: "25px", scale: "1.2" }, { duration: 300 })`

but in newer V2 u must use transform before it to transforms include in one property

`$element.velocity({ transform: "translateX(25px) scale(1.2)" }, { duration: 300 })`

i like fewer version (V1.5.0 transform) besause make our code cleaner and better understanding 
in new version transform Duration just apply to first transform property ;(((

**Comment by Rycochet** [comment] 2018-02-12 15:00
We're aiming to be able to have a stable release by the beginning of March - but need to make sure it's stable and complete enough to do that, so the date may slip slightly.

The old named animations (UI-Pack and Sequences) are being merged into one "sequences" module that I'm working on now - I'll also bring in some of the newer transitions from (animate.css)[https://daneden.github.io/animate.css/] when done.

Do remember to check the console for any errors, and report any bugs or unexpected behaviours that you come across - it might be as simple as missing or non-obvious documentation (which needs help!) ;-)

**Comment by riiccardo** [comment] 2018-02-12 18:29
thanks for answer the really important question 😍 👍 ...

what about newer features ?? morph or draw svg or some thing like this 
to make velocity fans bigger ;)


I'm not expecting this at the time, but if that happens, it's really great,

Good Luck bro ;)

;) موفق باشی داداش 

❤️

**Comment by Rycochet** [comment] 2018-02-12 22:47
Glad you figured out your bits for the new version. It is possible to add the old style translateX / scaleX type back in, and I'll probably give some example to do it - the issue is that it doesn't work well when you're using them together, so there were work-arounds for order and to prevent over-riding each other, and they didn't work as well as they can if using true css there.

SVG attributes are fully animatable too - and will happily work for anything, however - if you say wanted to animate a polygon from nothing to a shape and back again there are some caveats: if you use forcefeeding then you *must* make sure the number of points are equal, if you don't then it will replace any digits in the end value with the repeated digits in the start value (so if you set the property first to "200,100" then add an animation with three pairs of points they'll all be animated from that "200,100" point - if you don't set it then it'll replace all numbers with "0" instead). It also is a true animation, so increasing the length of the line isn't possible without some other code to handle it (I might add an easing for that at some point - which would need specific code to handle).

**Comment by riiccardo** [comment] 2018-02-13 10:00
thanks for it :rose: 
most of us want better documentation for V2 and don't want add more basic example :abc:  :|
I mean,
You do not need to visit stackoverflow for every small question... or maybe big :D

pls include more advanced examples for ![rsz_1rsz_svg_logosvg](https://user-images.githubusercontent.com/17789047/36143981-e8461654-10c1-11e8-9722-3e650ef7ea2d.png) and update site doc :hammer: in march

goodluck have fun

**Comment by Rycochet** [comment] 2018-05-28 11:59
Running somewhat late, see #851 for updates - I'm putting as much time in as I can right, now, trying to lock down final important bugs and get the documentation updated.

**Closed by Rycochet** 2018-05-28 11:59 UTC
Labels: IMPORTANT
