### ISSUE TITLE
http://velocityjs.org/  insecure connection

### ISSUE THREAD

**Issue by leela52452** [julianshapiro/velocity#913] opened 2019-10-26 11:46 UTC
@julianshapiro 
excuse...

![Screenshot_2019-10-26-17-02-34](https://user-images.githubusercontent.com/52065244/67619037-1ea24300-f7e6-11e9-87ba-5e0ad45debbf.png)

**Comment by pygy** [comment] 2019-12-15 20:45
Yup, there's an issue with the certificate on https://velocityjs.org/:

> *An error occurred during a connection to velocityjs.org. SSL received a record that exceeded the maximum permissible length.

> Error code: SSL_ERROR_RX_RECORD_TOO_LONG*

**Comment by Rycochet** [comment] 2020-04-10 13:08
Duplicate of #859

**Closed by Rycochet** 2020-04-10 13:08 UTC
