### ISSUE TITLE
Why does the npm package velocity-animate depend on jQuery?

### ISSUE THREAD

**Issue by joshburgess** [julianshapiro/velocity#678] opened 2016-05-20 18:25 UTC
Haven't yet looked at the internals to see how/if it's being used, but pulling Velocity into a project that uses npm through the velocity-animate module pulls down jquery@2.2.4 as a dependency...

If you can use Velocity completely without jQuery, why is it including it as a depenency here? Shouldn't we be able to use this while excluding jQuery?

**Comment by Rycochet** [comment] 2016-05-21 02:03
Duplicate of #497

**Closed by Rycochet** 2016-05-21 02:03 UTC
