### ISSUE TITLE
jQuery dependency in bower.json

### ISSUE THREAD

**Issue by djskinner** [julianshapiro/velocity#609] opened 2015-11-24 09:43 UTC
I read somewhere that velocity no longer requires jQuery yet it is a listed dependency in bower.json. Is it still required?

**Comment by Rycochet** [comment] 2015-11-24 10:25
There's a jQuery shim so it's not required - and an open issue #542 relating to it.

**Comment by kenwheeler** [comment] 2016-01-19 14:42
I'm going to close this as a dupe of 542

**Closed by kenwheeler** 2016-01-19 14:42 UTC
