### ISSUE TITLE
Thransition is changing site or links opacity

### ISSUE THREAD

**Issue by danyj** [julianshapiro/velocity#558] opened 2015-07-30 13:14 UTC
I am not sure which one this is but any transition applied to velocity element is affecting the site links opacity or maybe the page opacity itself. 

See this video  please
http://screencast.com/t/mnn3X9y5cI

in the video I am refreshing the page 3 times, 
pay attention to the menu links color , on page load they go darker by few % and when transition is over the normal color comes back .
This is transition used, but I tested with few others like slideIn slideLeftIn etc, and same thing. 

    $('.notification').css('display','none').velocity("transition.flipXIn");

am I missing something ?

**Comment by ydaniv** [comment] 2015-07-30 13:18
Sorry, either you can reproduce the issue in a fiddle/codepen or move this to StackOverflow

**Comment by danyj** [comment] 2015-07-30 13:19
@ydaniv  on fiddle in a few

**Comment by danyj** [comment] 2015-07-30 13:29
@ydaniv  here it is bud , same bug
https://jsfiddle.net/nz7z6pcq/

**Comment by ydaniv** [comment] 2015-07-30 13:33
Sorry, what should I be seeing?

**Comment by danyj** [comment] 2015-07-30 13:34
Pay attention to the links color in the menu , they change on load until animation is done, 
if you remove the animation the color stays as it is in css

**Comment by danyj** [comment] 2015-07-30 13:38
@ydaniv  here is better example with red links color 
https://jsfiddle.net/nz7z6pcq/1/

**Comment by ydaniv** [comment] 2015-07-30 14:01
Looks like a weird font antialiasing bug in Chrome. Doesn't happen on FF.

**Comment by danyj** [comment] 2015-07-30 14:03
Yes , and I just tested with animate.css  and same issue,  I think is connected to translate3d.

**Comment by ydaniv** [comment] 2015-07-30 14:04
OK, thanks. You can close it here and open for [chromium](https://code.google.com/p/chromium/issues/list) :+1:

**Closed** 2015-07-30 14:22 UTC
