### ISSUE TITLE
translateX triggers a lot of layer tree updates and painting

### ISSUE THREAD

**Issue by thehappycoder** [julianshapiro/velocity#593] opened 2015-10-13 14:14 UTC
In comparison, similar CSS3 animation works perfectly.

Is it a bug or normal situation?

**Comment by tommiehansen** [comment] 2015-10-29 13:00
Not a bug, but animating stuff isn't as easy as simply dropping some animation code on something unfortunately. It really do take some planning to make sure that one animates as wisely as possible.

What often happens when people animate things via CSS3 is that they also, even if they don't know it,  create layers and thus causes less bad paints.

Try adding `backface-visibility:hidden` to elements you're animating with Velocity or cheat by doing:

`.velocity-animating { backface-visibility: hidden; }`

..or

`.velocity-animating { transform: translateZ(0); }` (will ofc not work on things where you animate translateZ)

And see if that make any difference.

**Comment by thehappycoder** [comment] 2015-11-27 13:26
Will try backface-visibility trick.

**Comment by kenwheeler** [comment] 2016-01-19 16:16
Closing, if you think this is in error, please provide a JSFiddle and I can take a look and reopen if necessary

**Closed by kenwheeler** 2016-01-19 16:16 UTC
